language: node_js
sudo: required

services:
  docker

before_install:
  - docker build -t oopjot/pizza-app .

script:
  - npm test
  - npm run build

# after_success:
#   - docker build -t oopjot/pizza-app .