service:
  docker

before_install:
  - docker build -t oopjot/pizza-app -f Dockerfile .

script:
  - docker run oopjot/pizza-app npm run test

# after_success:
#   - docker build -t oopjot/pizza-app .